### ISSUE TITLE
Converted epubs are uploaded to Kobo reader as ebookname.kepub.epub

### ISSUE THREAD

**Issue by leavion** [jgoguen/calibre-kobo-driver#140]
Calibre: 5.32 [64bit]
KoboTouchExtended 3.5.4

I recently noticed that epubs that are sent to my Kobo no longer show up as kepubs but as epubs only. When I removed the ebook from the device using the Calibre interface I noticed that the file name is *.kepub.epub so I assume this causes the Kobo device to handle it as a regular epub file. This is not ebook specific but happens with all ebooks.

[Calibe Log.txt](https://github.com/jgoguen/calibre-kobo-driver/files/7612923/Calibe.Log.txt)

**Comment by jgoguen** [comment]
According to the log you provided, Kobo spans are already present in the file so there's nothing for the conversion to do. The file name uploaded is correct, KePub files are defined as having the double `.kepub.epub` extension. Calibre doesn't support double extensions so KePub files are stored in calibre with only a `.kepub` extension, but the Kobo reader requires `.kepub.epub` to treat a book as a KePub file.

To troubleshoot this further, I'll need more information as requested in the new issue template. Please open a new issue and provide as much information as you can using the provided template. Since this is happening with all books, you can scramble any book giving you trouble and include both the ePub and KePub formats.

**Comment by le-avion** [comment]
Just wanted to add some information that probably will not help but it is curious enough to mention. After I ran Calibre in debug mode to get the log file, all of a sudden all my epub books are now converted properly to kepub when uploaded to the Kobo Format and display as such.
