### ISSUE TITLE
Updating an existing ebook on device does not take new pages into account

### ISSUE THREAD

**Issue by victornoel** [jgoguen/calibre-kobo-driver#156]
# Bug Checklist

These items are mandatory. If you need help finding this information submit the
bug report with as much completed as you can and ask for help finding the rest.

- [x] I am using the latest version of calibre to report this bug, which is: 6.10
- [ ] I am using an official calibre release, not one from a third party (e.g.
    your Linux distro, Flatpak, Chocolatey package, Homebrew, etc.)
- [x] I am using the latest version of this plugin, which is: KoboTocyhExtended 3.6.3
- [x] My operating system is (e.g. Windows 10, Windows 8.1, Windows 8, macOS
    10.15.5, Fedora 32, Arch Linux, etc.): Archlinux
- [ ] I have included the full, complete, unmodified debug log from calibre
  - Directions for getting the debug log are under the "Logs" header below.
- [ ] I have translated the text in any screenshots and logs to English, or all
    screenshots and logs included are in English.

These items are optional. Fill in as much of them as possible. If something is
not applicable to your bug report, note that.

- [ ] I have installed the Scramble Epub plugin (see
    https://www.mobileread.com/forums/showthread.php?t=267998) and will attach
    a **scrambled** copy of the book I'm having problems with (attach a file by
    dragging and dropping onto the Github editor).
  - [ ] If this is a conversion bug, I will also attach a **scrambled** copy of
    the converted book.
- [ ] The path to my calibre library or to a book in my calibre library has
    non-ASCII characters: yes/no
- [ ] If I am using Windows 10, I (have/have not) enabled Windows' beta support
      for Unicode (see
      https://www.mobileread.com/forums/showpost.php?p=3988195&postcount=2052)
- [ ] If I am using Windows 10, does this bug happens with beta Unicode support
    both enabled and disabled, only when enabled, or only when disabled?

# Describe the bug

I have an epub that was sent to my kobo clara e2 (and automatically converted to kepub of course), after updating the epub (adding some more pages at the end) on my computer, I sent it again to the device, but when I open it on the device, I cannot see the new pages even though the size of the file is correct on the device

It worked well in the past with my bookeen device.

## Steps to Reproduce

Steps to reproduce the behavior (as detailed as you can):

1. Create a one page epub with libreoffice (create a document, export it to epub 3.0)
1. add it to calibre, send it to device, read it there
1. add one more page to the epub (add a page in the document, export it again)
1. update the epub file in calibre and send it again to the device
2. the size of the kepub is updated on the device in the menus but when I open it, I cannot see the new pages

## Expected behavior

I would expect that I can open the kepub on the device, be back on the page where I last was but now there are new pages so that I can continue reading.

## Actual behaviour

the new pages are missing

## Additional context

I haven't included all logs and co. I can do it if you think this is needed to investigate what's happening :)

**Comment by jgoguen** [comment]
I'm not able to reproduce this with my setup, but can you try using the Kobo Utilities plugin to update the ToC?

- Install the "Kobo Utilities" plugin and restart calibre
- Send a book to the device, unmount, verify the book is added
- Reconnect the device, send an updated book
- Disconnect, then reconnect once the device is done processing updates
- In the Kobo Utilities extension menu, choose "Update ToC for Selected Books"
- Disconnect again, the book should be updated now

If that still doesn't work, please download the official calibre distribution, not an Arch or AUR package, and try to reproduce it with the official release. Even if it's the same in the official distribution, finding out what happens here might give me some idea of what's happening or how I can try to reproduce it on my end.

**Comment by victornoel** [comment]
@jgoguen yes, it works as you describe it :+1:

**Comment by victornoel** [comment]
hi @jgoguen I see you closed the issue but I don't see any changes in the plugin, does it mean that the only solution for this problem is to manually "Update the ToC for Selected Books"?

**Comment by jgoguen** [comment]
Sorry! Yes, that's all you can do I think. The behavior you're describing indicates the ePub index is out of order. It's entirely possible there's something I'm missing, and if so please feel free to reopen this with details, but I don't think I can detect when the index is incorrectly ordered. I also don't want to go forcibly updating the ToC if it isn't needed.

**Comment by victornoel** [comment]
Ok and I guess there is no way to detect that we are pushing an epub on the device that already exists there? Something like this when we push an epub to the device:
- check if epub exists, maybe get a checksum or last change date or anything that could help detect the content changed
- push the new epub, get the same checksum or anything else
- update TOC (and any other required metadata) if checksums do not match

I'm pretty sure things may be more complex than this but well, I'm trying to invent ideas :P thx!

**Comment by jgoguen** [comment]
The KePub conversion process doesn't guarantee stable checksums. It hasn't been a priority since it's never been needed for anything. I don't believe calibre stores anything I could reliably use as a "last changed" time either. But storing the last changed time for the Kobo book would mean additional files to manage and clean up. If something like this is going to be implemented, it'll have to wait for stable checksums to be a guarantee. But even then, I'm not sure a ToC update belongs in this plugin. If the TOC is broken in the KePub version, it's also broken in the ePub version, and this plugin is generally focused on KePub-specific things.

**Comment by victornoel** [comment]
@jgoguen this makes sense yes, as I see it, your plugin is responsible of converting to kepub, not to properly implement the ingestion of kepub by the device.

So now I'm wondering if this is a bug in the kobo software itself then, no? Would you be aware of the proper way of reporting such a bug?

**Comment by jgoguen** [comment]
It depends. What it sounds like to me is the KePub is being properly ingested by the device, but the ePub spine (the location where the reader finds the default reading order of the individual files within the ePub container) is incorrect. Which, since you're adding a new chapter, seems odd. But I realize you didn't say how you're adding the new chapter. Are you using the calibre book editor for that, or something else?

You can look at what the ToC looks like for the book, based on the spine data, in the calibre book editor. Right-click the book in your library and choose "Edit Book" (default shortcut key: T). Then, along the top bar, find the icon for "Edit Table of Contents". That will show you the book's ToC and allow you to edit it. Selecting an existing entry should show you where it points to (down along the bottom of the window).

**Comment by jgoguen** [comment]
It depends. What it sounds like to me is the KePub is being properly ingested by the device, but the ePub spine (the location where the reader finds the default reading order of the individual files within the ePub container) is incorrect. Which, since you're adding a new chapter, seems odd. But I realize you didn't say if you've checked the book with the calibre book editor. Can you try that?

You can look at what the ToC looks like for the book, based on the spine data, in the calibre book editor. Right-click the book in your library and choose "Edit Book" (default shortcut key: T). Then, along the top bar, find the icon for "Edit Table of Contents". That will show you the book's ToC and allow you to edit it. Selecting an existing entry should show you where it points to (down along the bottom of the window).


The book editor also has a few other nice features, some only in menu options, like upgrade book internals to ePub 3, auto-fix correctable errors, and show all errors with the book. And since a KePub is just a regular ePub with some extra markup in the actual content files, you can treat a KePub exactly like an ePub (in fact, any ePub reader should be able to read a KePub).
